apiVersion: v1
kind: Service
metadata:
  name: tekton-app
  labels:
    app: tekton-app
spec:
  ports:
    - port: 8080
  #      targetPort: http-server
  selector:
    app: tekton-app
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tekton-app
  labels:
    app: tekton-app
spec:
  selector:
    matchLabels:
      app: tekton-app
  template:
    metadata:
      labels:
        app: tekton-app
    spec:
      containers:
        - name: tekton-app
          image: __IMAGE__@__DIGEST__
          imagePullPolicy: Always
          ports:
            - name: http-server
              containerPort: 8080

